.TH sde-logout 1 "Mar 21, 2008" "sde-logout"

.SH NAME
sde-logout \-program for...

.SH SYNOPSIS
.B sde-logout
.br

.SH DESCRIPTION
This manual page explains the
.B sde-logout
program. This program is part of SDE.
.PP
\fBsde-logout\fP, as its name implies, is for logging out SDE.
Running this program will show the logout dialog on the screen.

.SH SEE ALSO
startsde

.SH AUTHOR
Hong Jen Yee <pcman.tw@gmail.com>