.TH startsde 1 "Sep 22, 2020" "startsde"

.SH NAME
startsde \- X session script to prepare environment and run sde-session-manager.

.SH SYNOPSIS
.B startsde
.br

.SH DESCRIPTION
.PP
\fBstartsde\fP is used to start the desktop session of SDE.
It adjusts the environment variables, starts dbus-launch and sde-session-manager.
.PP
\fBsde-session-manager\fP then normally starts openbox, waterline, stuurman, stuurman-desktop and xscreensaver.

.SH AUTHOR
Vadim Ushakov <igeekless@gmail.com>
.PP
Hong Jen Yee <pcman.tw@gmail.com>
