{
  "global": {
    "edge": "left",
    "align": "left",
    "edge_margin": 0,
    "align_margin": 0,
    "oriented_width_type": "percent",
    "oriented_width": 100,
    "oriented_height": 75,
    "round_corners": false,
    "round_corners_radius": 7,
    "rgba_transparency": true,
    "stretch_background": false,
    "background": false,
    "transparent": true,
    "alpha": 55,
    "tint_color": "#000000",
    "visibility_mode": "always",
    "height_when_hidden": 1,
    "set_strut": 1,
    "use_font_color": true,
    "font_color": "#ffffff",
    "use_font_size": false,
    "font_size": 10,
    "icon_size": 64,
    "padding_top": 2,
    "padding_bottom": 2,
    "padding_left": 2,
    "padding_right": 2,
    "applet_spacing": 2,
    "GtkWidgetName": "PanelToplevel",
    "output_target": "primary_monitor",
    "custom_monitor": 0,
    "background_file": "",
    "background_mode": "color",
    "background_color": "#000000"
  },
  "plugins": [
    {
      "settings": {
        "tooltips": true,
        "show_icons_titles": "Icons",
        "custom_fallback_icon": "xorg",
        "show_iconified": true,
        "show_mapped": true,
        "show_all_desks": false,
        "show_urgency_all_desks": true,
        "use_urgency_hint": true,
        "flat_inactive_buttons": true,
        "flat_active_button": false,
        "colorize_buttons": true,
        "use_thumbnails_as_icons": true,
        "dim_iconified": true,
        "task_width_max": 200,
        "spacing": 1,
        "highlight_modified_titles": false,
        "highlight_title_of_focused_button": false,
        "bold_font_on_mouse_over": false,
        "mode": "Group",
        "group_fold_threshold": 8,
        "panel_fold_threshold": 10,
        "group_by": "Class",
        "manual_grouping": true,
        "unfold_focused_group": false,
        "show_single_group": false,
        "show_close_buttons": false,
        "sort_by[0]": "Timestamp",
        "sort_by[1]": "Timestamp",
        "sort_by[2]": "Timestamp",
        "sort_reverse[0]": false,
        "sort_reverse[1]": false,
        "sort_reverse[2]": false,
        "rearrange": false,
        "button1_action": "RaiseIconify",
        "button2_action": "Shade",
        "button3_action": "Menu",
        "scroll_up_action": "PrevWindow",
        "scroll_down_action": "NextWindow",
        "shift_button1_action": "Iconify",
        "shift_button2_action": "Maximize",
        "shift_button3_action": "Close",
        "shift_scroll_up_action": "PrevWindowInCurrentGroup",
        "shift_scroll_down_action": "NextWindowInCurrentGroup",
        "menu_actions_click_press": "Press",
        "other_actions_click_press": "Click",
        "mouse_over_action": "ShowPreview",
        "use_group_separators": false,
        "group_separator_size": 0,
        "hide_from_launchbar": true,
        "use_x_net_wm_icon_geometry": false,
        "use_x_window_position": false
      },
      "type": "taskbar",
      "expand": true,
      "padding": 0,
      "border": 0,
      "icon_size": 0
    },
    {
      "settings": {
        "volume_control_command": "",
        "alpha_blending_enabled": true
      },
      "type": "volumealsa",
      "expand": false,
      "padding": 0,
      "border": 0,
      "icon_size": 0
    },
    {
      "settings": {
        "display_in_frame": true,
        "use_custom_icon_size": true,
        "icon_size": 16
      },
      "type": "notification_area",
      "expand": false,
      "padding": 0,
      "border": 0,
      "icon_size": 0
    },
    {
      "settings": {
        "normal_color": "#00ff00",
        "warning1_color": "#fff000",
        "warning2_color": "#ff0000",
        "autoselect_warning_levels": true,
        "warning1_temperature": 89,
        "warning2_temperature": 94,
        "autoselect_sensor": false,
        "sensor": "/sys/class/thermal/thermal_zone0/"
      },
      "type": "thermal",
      "icon_size": 0,
      "expand": false,
      "padding": 0,
      "border": 0
    },
    {
      "settings": {
        "hide_if_no_battery": false,
        "alarmCommand": "xmessage Battery low",
        "alarmTime": 5,
        "display_as": "Text",
        "background_color": "rgb(0,0,0)",
        "border_width": 3,
        "charging_color1": "rgb(27,59,198)",
        "charging_color2": "rgb(181,47,195)",
        "discharging_color1": "rgb(0,255,0)",
        "discharging_color2": "rgb(255,0,0)",
        "show_power_stats": true,
        "show_detailed_charge_stats": true
      },
      "type": "battery_indicator",
      "expand": false,
      "padding": 0,
      "border": 0,
      "icon_size": 0
    },
    {
      "settings": {
        "clock_format": "%R",
        "tooltip_format": "%A %x",
        "icon_only": false,
        "center_text": false,
        "action": "",
        "font": "PT Sans 15",
        "timezone": ""
      },
      "type": "dclock",
      "expand": false,
      "padding": 0,
      "border": 0,
      "icon_size": 0
    },
    {
      "settings": {
        "display_as_text": true,
        "per_window_layout": true,
        "default_group": 0
      },
      "type": "xkb_groups",
      "icon_size": 0,
      "expand": false,
      "padding": 0,
      "border": 0
    }
  ]
}